### PR TITLE
close child connection after first epipe

### PR DESCRIPTION
**Pull request by thillux**

### CODE REVIEW

**Comment by thillux** [comment]
Is this all what is needed or are we leaking resources now?

**Comment by thillux** [comment]
After reading the code, connection should be freed in esdm_rpcs_handler. Therefore marking it as ready.

```
ESDM (16:23:22) (ESDM unpriv_rpc) Debug - RPC [../service-rpc/server/esdm_rpc_server.c:esdm_rpcs_workerloop:676]: Processing new incoming connection for FD 6
ESDM (16:23:22) (ESDM unpriv_rpc) Verbose - Threading support [../common/threading_support.c:thread_schedule:385]: Thread 0 for thread group 0 allocated
ESDM (16:23:22) (ESDM unpriv_rpc) Verbose - Threading support [../common/threading_support.c:thread_schedule:399]: Thread 0 for thread group 0 assigned
ESDM (16:23:22) (ESDM hdl_rpc6) Debug [../service-rpc/server/esdm_rpc_server.c:esdm_rpcs_read:435]: Reading 16 bytes, already consumed 16 bytes
ESDM (16:23:22) (ESDM hdl_rpc6) Debug - RPC [../service-rpc/server/esdm_rpc_server.c:esdm_rpcs_read:454]: Server received: message length 4, message index 5, request ID 0
ESDM (16:23:22) (ESDM hdl_rpc6) Debug - DRNG [../esdm/esdm_drng_mgr.c:esdm_drng_seed_work_one:509]: reseed triggered by system events for DRNG on node 0
ESDM (16:23:22) (ESDM hdl_rpc6) Debug - Entropy Source [../esdm/esdm_es_aux.c:esdm_aux_get_pool:354]: obtained 0 bits by collecting 0 bits of entropy from aux pool, 0 bits of entropy remaining
ESDM (16:23:22) (ESDM hdl_rpc6) Debug - DRNG [../esdm/esdm_drng_mgr.c:esdm_drng_inject:366]: seeding regular DRNG with 48 bytes
ESDM (16:23:22) (ESDM hdl_rpc6) Debug - DRNG [../esdm/esdm_drng_mgr.c:esdm_drng_inject:379]: regular DRNG stats since last seeding: 3 secs; generate calls: 0
ESDM (16:23:32) (ESDM hdl_rpc6) Debug - RPC [../service-rpc/server/esdm_rpc_server.c:esdm_rpcs_pack_internal:202]: Server sending: server status 0, message length 11, message index 5, request ID 0
ESDM (16:23:32) (ESDM hdl_rpc6) Debug [../service-rpc/server/esdm_rpc_server.c:esdm_rpcs_read:435]: Reading 16 bytes, already consumed 16 bytes
ESDM (16:23:32) (ESDM hdl_rpc6) Debug - RPC [../service-rpc/server/esdm_rpc_server.c:esdm_rpcs_read:454]: Server received: message length 4, message index 5, request ID 0
ESDM (16:23:32) (ESDM hdl_rpc6) Debug - DRNG [../esdm/esdm_drng_mgr.c:esdm_drng_seed_work_one:509]: reseed triggered by system events for DRNG on node 0
ESDM (16:23:32) (ESDM hdl_rpc6) Debug - Entropy Source [../esdm/esdm_es_aux.c:esdm_aux_get_pool:354]: obtained 0 bits by collecting 0 bits of entropy from aux pool, 0 bits of entropy remaining
ESDM (16:23:32) (ESDM hdl_rpc6) Debug - DRNG [../esdm/esdm_drng_mgr.c:esdm_drng_inject:366]: seeding regular DRNG with 48 bytes
ESDM (16:23:32) (ESDM hdl_rpc6) Debug - DRNG [../esdm/esdm_drng_mgr.c:esdm_drng_inject:379]: regular DRNG stats since last seeding: 10 secs; generate calls: 0
ESDM (16:23:42) (ESDM hdl_rpc6) Debug - RPC [../service-rpc/server/esdm_rpc_server.c:esdm_rpcs_pack_internal:202]: Server sending: server status 0, message length 11, message index 5, request ID 0
ESDM (16:23:42) (ESDM hdl_rpc6) Verbose - RPC [../service-rpc/server/esdm_rpc_server.c:esdm_rpcs_write_data:136]: Writting of data to file descriptor 6 failed: Broken pipe
ESDM (16:23:42) (ESDM hdl_rpc6) Error [../service-rpc/server/esdm_rpc_server.c:esdm_rpcs_pack_internal:216]: Submission of message data failed with error -32
ESDM (16:23:42) (ESDM hdl_rpc6) Error [../service-rpc/server/esdm_rpc_server.c:esdm_rpcs_response_closure:341]: Failed to serialize response: -32
ESDM (16:23:42) (ESDM hdl_rpc6) Debug - RPC [../service-rpc/server/esdm_rpc_server.c:esdm_rpcs_handler:532]: Closing incoming connection for FD -1
ESDM (16:23:42) (ESDM hdl_rpc6) Verbose - Threading support [../common/threading_support.c:thread_worker:256]: Thread 0 completed
```

**Comment by smuellerDD** [comment]
I updated the patch a bit to not receive an EBADFD. Please check.

**Comment by thillux** [comment]
Works for me!

**Pull request closed without merging**
